[workspace]
members = [
    "./src/backend/statistics",
    "./src/backend/payment_hub",
    "./src/backend/payment_hub_history",
]
resolver = "1"

[profile.release]
codegen-units = 1
strip = true
lto = true
opt-level = 'z'
panic = 'abort'
